fixed issue while testing GUI
Once we click on Update Favorites it always stay in blue hi lighted color.  Done
If we click on specific blog then one confirmation box pop-up.
No difference between Discover and Update Favorite.
My Profile is empty.  NA
If I register with other username and login then, in create blog I see the blog which are created by other users in bottom, while we should show only our own blog in create blog.   Done
Sometimes blogs shown below the create blog is not complete list. NA
Sometimes search Blog does not work.
After Signing out still we say the registration message “Hi : kar you are succesfully registered”
sometimes Welcome message is not coming on top of My Profile
In chat, messages are keep appending, we might need to empty the chat before logging out.   Done
If we are posting empty its getting posted.     Done
Same with comments.  Done
Click on MyProfile, Click on Create blog, it still shows my profile under Create blog.  Done
Click on Discover, Click on Create blog, it still shows Discover under Create blog.   Done
Click on My blogs, Click on Create blog, it still shows My Blogs under Create blog.  Done
Below error:
Jan 31, 2017 7:00:56 PM org.apache.catalina.core.StandardWrapperValve invoke

SEVERE: Servlet.service() for servlet [jersey] in context with path [/BloggersInn] threw exception

org.hibernate.HibernateException: The internal connection pool has reached its maximum size and no connection is currently available!

Done